### ISSUE TITLE
please deprecate when u change something

### ISSUE THREAD

**Issue by muhasturk** [Yalantis/Koloda#144]
you've changed lots of protocol methods and you forgot to include warning to us.

**Comment by AEugene** [comment]
hi @muhasturk . I did intentionally. You see, code `@available(*, deprecated=3.0.0, renamed="Something")` doesn't give warning in compiler and doesn't indicate marked method in XCode autocomplete. There is another option - to make it like this `@available(*, unavailable)`, and it gives error in compiler, but this works only with `@objc` marker. In version 3.0.0 I only moved parameter label to method name in naming of delegate methods. That's why there would be methods with same names and it could cause misunderstandings in autocomplete. I've listed all changes in release log: https://github.com/Yalantis/Koloda/releases/tag/3.0.0
If you know how to resolve this issue, I would appreciate your help.

**Comment by AEugene** [comment]
@muhasturk does it make sense?
