### ISSUE TITLE
Kolodaview is rotating away from swipe direction

### ISSUE THREAD

**Issue by zubair** [Yalantis/Koloda#277]
@AEugene 
@freaqed 
# Report
Kolodaview is rotating away from swipe direction when you begin swipe from lower than the view's center. I would like to keep the functionality that is shown in the example and disable this functionality.

The Problem:
![demonstration](https://cloud.githubusercontent.com/assets/13080927/25020513/809a4e36-2043-11e7-87cf-83af88cd08bb.gif)
Example Demonstration:
![koloda_v2_example_animation](https://cloud.githubusercontent.com/assets/13080927/25020871/f018ef78-2044-11e7-9f24-fa65a22ad097.gif)

**Comment by z0s** [comment]
Has anyone reached a viable solution?

**Comment by ElChepa** [comment]
if you want to prevent the rotation upwards, you could do it by editing the DraggableCardView class implemented by the koloda framework. You have to change one property in the ".began" case of the switch statement in the implementation of the "panGestureRecognized" method.

Change this line from this: 
`animationDirectionY = touchLocation.y >= frame.size.height / 2 ? -1.0 : 1.0`

To this: 
`animationDirectionY = 1`
  
This way the CardView will always rotate downwards regardless of the user interaction.

**Comment by freaqed** [comment]
@ElChepa thanks for a good solution.
@zubair Koloda is developed to solve some problems, not all of them. Extending component to support such features will cause codebase to extremely grow and any new users will have to dive deep into API in order to understand what exactly they need to do for basic usage. 
So please, try the solution above.
