### ISSUE TITLE
Removing the Swipe Feature

### ISSUE THREAD

**Issue by alexalbertt** [Yalantis/Koloda#346]
Hi, thank you so much for creating Koloda View! I was wondering if there was a way to disable swiping of the cards and instead have the user only be able to use the buttons. Thanks!

**Comment by freaqed** [comment]
Hello, @alexalbertt! Thanks :)

Currently, KolodaView doesn't have API for such purpose. And I don't think we'll add it since it's a rare case of use.
My suggestion here is put transparent view with enabled userInteraction above KolodaView in order to intercept interactions. Not so good solution, but I don't see any other
