### ISSUE TITLE
Display placeholder when card runs out.

### ISSUE THREAD

**Issue by mteera** [Yalantis/Koloda#365]
I am attempting to display a placeholder when cards run out. I know how to implement it to the ` func kolodaDidRunOutOfCards(_ koloda: KolodaView)` where I try `placeholderView.isHidden = false`. But I need to set the placeholder on initial launch as well if there are no cards to be displayed.

Thank you in advance.

**Comment by rnkyr** [comment]
Hello, @mteera
The answer to your question depends on context. How are you load your data, is there any initial value, which pattern are you using for observing data changes and so on. The general answer - just check your data source once it's loaded and show your empty state placeholder.
Closing the issue since it's not related to Koloda itself.
