### ISSUE TITLE
Using custom UIView for Cards

### ISSUE THREAD

**Issue by esteven1234** [Yalantis/Koloda#408]
###  What did you do?

> I'm trying to figure out how best to create custom cards where instead of just an image, I could display a name/hometown/etc, but have run into great trouble trying to use custom UIViews, I was wondering if there is standard protocol for performing such a task?

### What did you expect to happen?

> Hoping to get custom cards similar to the ones displayed in the readme images.  

### What happened instead?

> Lots and lots of custom uiview errors.

### Your Environment

- Version of the component: _insert here_
- Swift version: _insert here_
- iOS version: _insert here_
- Device: _insert here_
- Xcode version: _insert here_
- If you use Cocoapods: _run `pod env | pbcopy` and insert here_ 
- If you use Carthage: _run `carthage version | pbcopy` and insert here_

### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.

**Comment by esteven1234** [comment]
I'd like to add that I'm looking for the simplest possible solution to solve this problem, very basic needs just looking for some kind of custom view for the card.

**Comment by den-zv** [comment]
Hey! You can just use `KolodaViewDataSource`'s method to set your custom view as a card view (`koloda(_ koloda: KolodaView, viewForCardAt index: Int) -> UIView`). Usage is the same as in example but you can return any `UIView` subclass instead of image in this method.

> Lots and lots of custom uiview errors.
It seems to be a problem in your custom view implementation (maybe some issues with constraints, initialization, etc). We need more information about these error to be able to say something else.

Closing this issue.
Please ping us back with more information in case problem is still there.
