### ISSUE TITLE
removing card at particular index

### ISSUE THREAD

**Issue by sunilhs1986** [Yalantis/Koloda#421]
Hi All,

I would like to remove card at particular index after swipe. Can someone please help on this ?

Regards
Sunil

**Comment by den-zv** [comment]
Hey! You can remove cards the same way you can insert cards. Please refer to answer in #417 .

Closing this issue.
Please ping us back with more information in case problem is still there.

**Comment by MandeepSingh1** [comment]
You can delete your card from particular index. They have provide the method but doesn't explain it how to delete the card.

1. First of all you have to check the current card Index of your Koloda View.
2. Then remove the value from your array according to your index. 
3. Then in removeCardInIndexRange method you have to pass the value of range. Now what is this range, this is the difficult part one.
4. In my case when ever I swipe the card the index value would be provided by method of Koloda view and the position would be of your current Card Index which am using in below Method.

 func koloda(_ koloda: KolodaView, didSwipeCardAt index: Int, in direction: SwipeResultDirection) {
        let position = kolodaView.currentCardIndex
        self.userArrayList.remove(at: index)
        self.kolodaView.removeCardInIndexRange(index..<position, animated: false)
    }

By using the above method you can easily delete the value from your array and Koloda view. Make sure the range would be correct otherwise the application would be crashed.
