### ISSUE TITLE
when Drag and Hold a card,the border of frame might show and center might change

### ISSUE THREAD

**Issue by byoungd** [Yalantis/Koloda#86]
when drag and hold a card

the border of card frame might flash , woo~~

and if you hold the card for Too Long Time

the card can't go back ,the center of the card changed?

**Comment by AEugene** [comment]
Hi @byoungd , which version of Koloda do you use?
First issue could be caused by autolayout in previous Koloda versions. Latest version animations are build up on layer transforms, so it shouldn't appear.
I wasn't able to reproduce second issue. Could you give us some steps and sample code, so we can better understand the issue?
