### ISSUE TITLE
Minor issue with card frame size.

### ISSUE THREAD

**Issue by Bashta** [Yalantis/Koloda#89]
This in not a bug, but rather something to take in consideration for future releases. After using another lib in order to [detect the face to scale and fit](http://useyourloaf.com/blog/dynamically-loading-new-rows-into-a-table.html) the image properly in the card i noticed that the first image is set properly. The problem lies in the cards in background "countOfVisibleCards". After debugging i discovered that their frames are actually smaller than the actual visible card frame. This caused a strange behaviour oh the other lib actually setting a smaller image to the UIImageView, resulting in a white stripe showing on the left side of the card when the card comes on top. Setting the countOfVisibleCards to ! resolves the issue but it would be nice to have the option of non resizing the cards in background.

**Comment by AEugene** [comment]
Hi @Bashta 
Current implementation of background cards moving and layout is based on frame calculations, that's why their frames are smaller.
We're thinking about move all sizes and positions handling to layer transforms instead of view transforms and setting frames. But for now there is an option of non resizing the cards - you can implement your own frames calculation in subclass overriding:
```swift
    public func frameForCardAtIndex(index: UInt) -> CGRect 
```

**Comment by Bashta** [comment]
@AEugene Thank you for the heads up!

**Comment by AEugene** [comment]
hi @Bashta . Could you try #108 , issue might be fixed there?

**Comment by Bashta** [comment]
@AEugene  I'll give it a try tomorrow morning and let you know.

**Comment by Bashta** [comment]
@AEugene Just gave it a try and its working fine for me :+1: Thank you for the fix.
